# Generated by Django 4.2.6 on 2023-10-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0002_album_band_delete_post_album_band'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
